//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nprojet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoordonneesProfessionnelles
    {
        public long CoordonneId { get; set; }
        public int BarreauId { get; set; }
        public Nullable<long> ReferenceNational { get; set; }
        public int OrganeId { get; set; }
        public int SituationPId { get; set; }
        public Nullable<System.DateTime> AnneeDA { get; set; }
        public Nullable<System.DateTime> AnneeAY { get; set; }
        public int CourCassationId { get; set; }
        public Nullable<System.DateTime> AnneeACC { get; set; }
        public int StatutAHId { get; set; }
        public Nullable<System.DateTime> AnneeSt { get; set; }
        public Nullable<System.DateTime> AnneeRSt { get; set; }
        public int StatutCapitaineId { get; set; }
        public Nullable<System.DateTime> AnneeCapitaine { get; set; }
        public Nullable<System.DateTime> AnneeFinSt { get; set; }
        public int AvocatAssistantId { get; set; }
        public Nullable<long> NomAvocatAss { get; set; }
        public int AvocatParId { get; set; }
        public Nullable<long> NomAvocatPar { get; set; }
        public int AvocatCohId { get; set; }
        public Nullable<long> NomAvocatCoh { get; set; }
        public int AssuranceId { get; set; }
        public string NomSociete { get; set; }
        public Nullable<long> NomAvocatAssurance { get; set; }
        public long PartieId { get; set; }
    
        public virtual Assurance Assurance { get; set; }
        public virtual AvocatAssistant AvocatAssistant { get; set; }
        public virtual AvocatCoh AvocatCoh { get; set; }
        public virtual AvocatPar AvocatPar { get; set; }
        public virtual Barreau Barreau { get; set; }
        public virtual StatutAH StatutAH { get; set; }
        public virtual StatutCapitaine StatutCapitaine { get; set; }
        public virtual CourCassation CourCassation { get; set; }
        public virtual Juridiction Juridiction { get; set; }
        public virtual Partie Partie { get; set; }
        public virtual Partie Partie1 { get; set; }
        public virtual Partie Partie2 { get; set; }
        public virtual Partie Partie3 { get; set; }
        public virtual Partie Partie4 { get; set; }
        public virtual SituationP SituationP { get; set; }
    }
}
