//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nprojet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Databasee : DbContext
    {
        public Databasee()
            : base("name=Databasee")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assurance> Assurance { get; set; }
        public virtual DbSet<Audience> Audience { get; set; }
        public virtual DbSet<AvocatAssistant> AvocatAssistant { get; set; }
        public virtual DbSet<AvocatAssurance> AvocatAssurance { get; set; }
        public virtual DbSet<AvocatCoh> AvocatCoh { get; set; }
        public virtual DbSet<AvocatMembre> AvocatMembre { get; set; }
        public virtual DbSet<AvocatPar> AvocatPar { get; set; }
        public virtual DbSet<Barreau> Barreau { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<CatSanction> CatSanction { get; set; }
        public virtual DbSet<CoordonneesProfessionnelles> CoordonneesProfessionnelles { get; set; }
        public virtual DbSet<CourCassation> CourCassation { get; set; }
        public virtual DbSet<Decision> Decision { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Jugement> Jugement { get; set; }
        public virtual DbSet<Juridiction> Juridiction { get; set; }
        public virtual DbSet<Metier> Metier { get; set; }
        public virtual DbSet<Nationalite> Nationalite { get; set; }
        public virtual DbSet<Nomination> Nomination { get; set; }
        public virtual DbSet<Obtention> Obtention { get; set; }
        public virtual DbSet<Partie> Partie { get; set; }
        public virtual DbSet<PoursuiteJuridique> PoursuiteJuridique { get; set; }
        public virtual DbSet<Sanction> Sanction { get; set; }
        public virtual DbSet<SituationP> SituationP { get; set; }
        public virtual DbSet<Specialite> Specialite { get; set; }
        public virtual DbSet<Stage> Stage { get; set; }
        public virtual DbSet<StatutAH> StatutAH { get; set; }
        public virtual DbSet<StatutCapitaine> StatutCapitaine { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<Ville> Ville { get; set; }
    }
}
