//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nprojet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partie()
        {
            this.Audience = new HashSet<Audience>();
            this.AvocatMembre = new HashSet<AvocatMembre>();
            this.CoordonneesProfessionnelles = new HashSet<CoordonneesProfessionnelles>();
            this.CoordonneesProfessionnelles1 = new HashSet<CoordonneesProfessionnelles>();
            this.CoordonneesProfessionnelles2 = new HashSet<CoordonneesProfessionnelles>();
            this.CoordonneesProfessionnelles3 = new HashSet<CoordonneesProfessionnelles>();
            this.CoordonneesProfessionnelles4 = new HashSet<CoordonneesProfessionnelles>();
            this.Jugement = new HashSet<Jugement>();
            this.Obtention = new HashSet<Obtention>();
            this.Stage = new HashSet<Stage>();
            this.Stage1 = new HashSet<Stage>();
            this.PoursuiteJuridique = new HashSet<PoursuiteJuridique>();
            this.Sanction = new HashSet<Sanction>();
        }
    
        public long Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public string LieuNaissance { get; set; }
        public string Cin { get; set; }
        public string Adresse { get; set; }
        public int GenreId { get; set; }
        public int NationaliteId { get; set; }
        public int VilleId { get; set; }
        public int MetierId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audience> Audience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvocatMembre> AvocatMembre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoordonneesProfessionnelles> CoordonneesProfessionnelles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoordonneesProfessionnelles> CoordonneesProfessionnelles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoordonneesProfessionnelles> CoordonneesProfessionnelles2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoordonneesProfessionnelles> CoordonneesProfessionnelles3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoordonneesProfessionnelles> CoordonneesProfessionnelles4 { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jugement> Jugement { get; set; }
        public virtual Metier Metier { get; set; }
        public virtual Nationalite Nationalite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obtention> Obtention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stage> Stage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stage> Stage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PoursuiteJuridique> PoursuiteJuridique { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sanction> Sanction { get; set; }
        public virtual Ville Ville { get; set; }
    }
}
