//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nprojet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanction
    {
        public int SanctionId { get; set; }
        public System.DateTime DateSanction { get; set; }
        public long PartieId { get; set; }
        public long Id { get; set; }
    
        public virtual CatSanction CatSanction { get; set; }
        public virtual Partie Partie { get; set; }
    }
}
