//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nprojet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public int StageId { get; set; }
        public Nullable<System.DateTime> AnneeDebut { get; set; }
        public Nullable<System.DateTime> AnneeArret { get; set; }
        public Nullable<System.DateTime> AnneeReprendre { get; set; }
        public Nullable<System.DateTime> AnneFin { get; set; }
        public Nullable<System.DateTime> AnneeSupp { get; set; }
        public Nullable<long> AvocatStageId { get; set; }
        public long PartieId { get; set; }
    
        public virtual Partie Partie { get; set; }
        public virtual Partie Partie1 { get; set; }
    }
}
